FACET_ANCHORS = {
    "Analytical Reasoning": "I break problems into clear steps.",
    "Systems Perspective": "I see how parts fit a whole.",
    "Foresight": "I anticipate future outcomes.",
    "Curiosity": "I enjoy exploring new ideas.",
    "Reflective Learning": "I think about what I’ve learned.",
    "Sense-Making": "I turn data into clear stories.",
    "Ideation": "I generate many ideas quickly.",
    "Innovation": "I turn ideas into real projects.",
    "Aesthetic Sensitivity": "I notice small design details.",
    "Improvisation": "I adapt when plans change.",
    "Experimentation": "I test ideas to see what works.",
    "Synthesising": "I combine ideas into new concepts.",
    "Achievement Focus": "I aim for challenging goals.",
    "Discipline": "I stick to a task until done.",
    "Adaptable Execution": "I adjust plans when things change.",
    "Resilience": "I bounce back after setbacks.",
    "Initiative": "I act without being told.",
    "Efficiency": "I finish tasks in less time.",
    "Responsibility": "I own the outcomes of my work.",
    "Ethics": "I act according to my values.",
    "Reliability": "I deliver on time consistently.",
    "Patience": "I stay calm when waiting.",
    "Organising": "I keep tasks and data in order.",
    "Safety Orientation": "I take steps to avoid accidents.",
    "Empathy": "I feel others’ emotions.",
    "Social Awareness": "I read social cues accurately.",
    "Collaboration": "I cooperate toward shared goals.",
    "Trust Building": "I earn others’ confidence.",
    "Inclusiveness": "I welcome diverse viewpoints.",
    "Mentorship": "I help others develop skills.",
    "Persuasion": "I can convince others of my ideas.",
    "Storytelling": "I explain ideas through stories.",
    "Confidence": "I project self-assurance.",
    "Energising": "I lift group morale.",
    "Negotiation": "I reach deals that satisfy all sides.",
    "Vision Casting": "I paint a compelling future.",
}
