services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile    
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/stem_generation
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile    
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stem_generation
    ports:
      - "5432:5432"

volumes:
  postgres_data:
